language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  
matrix:
  allow_failures:
    - php: 5.5
  
before_script:
    - composer self-update
    - composer install

script: phpunit -c ./ --coverage-clover "clover"

after_success:
    - curl -sL https://bit.ly/artifact-uploader | php